data_dir: /data/LiftFly3D/prism/data_oriented/test_data'
#data_dir = '/data/LiftFly3D/prism/data_oriented/training_data'
#data_dir = '/data/LiftFly3D/optobot/network'
out_dir: '/data/LiftFly3D/DF3D/cam_angles/cam5'
#out_dir = '/data/LiftFly3D/DF3D/lift_vs_tri/test_dataset'
#out_dir = '/data/LiftFly3D/DF3D/behaviors/train_PR'
ndims: 38 #number of dimensions in dataset
in_dim: 2
out_dim: 1
dims_to_exclude: [15,16,17,18,34,35,36,37] #dimensions to not consider
train_subjects: [1,2,4] #[1,2,3,4] #for optobot (using all data here)
test_subjects: [3]
cam_id: 0
actions: ['PR'] #actions to load
interval: [] #[200,700] if only stimulation period
target_sets: [[ 1,  2,  3,  4],  [6,  7,  8,  9], [11, 12, 13, 14],
               [16, 17, 18, 19], [21, 22, 23, 24], [26, 27, 28, 29]]
#target_sets: [[ 2,  3,  4],  [7,  8,  9], [12, 13, 14], #for optobot
#               [17, 18, 19], [22, 23, 24], [27, 28, 29]]
roots: [0, 5, 10, 15, 20, 25]
scale: 1