data_dir: '/data/LiftPose3D/fly_ventral_highres/data'
template_dir: '/data/LiftPose3D/fly_ventral_highres/network/'
in_dim: 2
out_dim: 1
test_subjects: ['all']
actions: ['all'] #actions to load
target_sets: [[ 1,  2,  3,  4],  [6,  7,  8,  9], [11, 12, 13, 14],
               [16, 17, 18, 19], [21, 22, 23, 24], [26, 27, 28, 29]]
roots: [0, 5, 10, 15, 20, 25]