data:
  ndims: 20 # number of 2D/3D points for each time instance. number of joints tracked.
  in_dim: 2 # 2
  out_dim: 3 # 1 or 3.
  dims_to_exclude: [] #dimensions to not consider during lifting.
  roots: [3] # given targets will be predicted w.r.t roots. therefore len[roots] should be equal to len[targets].
  target_sets: [[0,1,2,3,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]]

vis: 
    bones: [[ 0,  1],
           [ 1,  2],
           [ 0,  2],
           [ 1,  3],
           [ 0,  3],
           [ 2,  3],
           [ 3,  4],
           [ 4,  5],
           [ 5,  8],
           [ 5,  9],
           [10, 11],
           [ 3, 12],
           [ 3, 13],
           [10, 12],
           [13, 15],
           [ 8, 17],
           [ 9, 16],
           [17, 18],
           [16, 19]]

           
    limb_id: [0, 0, 0, 5, 5, 5, 3, 3, 2, 1, 4, 4, 4, 6, 6, 6, 1, 2, 2, 1]
    
    colors:   [[  0.  ,   0.  , 255.  ],
               [  0.  , 127.5 ,   0.  ],
               [  0.  , 191.25, 191.25],
               [191.25,   0.  , 191.25],
               [191.25, 191.25,   0.  ],
               [255.  ,   0.  ,   0.  ],
               [255,     140,         0]]
             
    names: [['HeadF'],
             ['HeadB'],
             ['HeadL'],
             ['SpineF'],
             ['SpineM'],
             ['SpineL'],
             ['Offset1'],
             ['Offset2'],
             ['HipL'],
             ['HipR'],
             ['ElbowL'],
             ['ArmL'],
             ['ShoulderL'],
             ['ShoulderR'],
             ['ElbowR'],
             ['ArmR'],
             ['KneeR'],
             ['KneeL'],
             ['ShinL'],
             ['ShinR']]