data:
  ndims: 20 # number of 2D/3D points for each time instance. number of joints tracked.
  in_dim: 2 # 2
  out_dim: 3 # 1 or 3.
  roots: [3] # given targets will be predicted w.r.t roots. therefore len[roots] should be equal to len[targets].
  target_sets: [[0,3,5,8,9,10,11,12,13,15,16,17,18,19]]

vis: 
    bones: [[0,  3], #0
           [ 3,  4], #1
           [ 4,  5], #2
           [ 5,  8], #3
           [ 5,  9], #4
           [10, 11], #5
           [ 3, 12], #6
           [ 3, 13], #7
           [10, 12], #8
           [13, 15], #9
           [14, 15], #10
           [ 8, 17], #11
           [ 9, 16], #12
           [17, 18], #13
           [16, 19]] #14
           
    leaves: [0, 18, 19, 11, 15]
             #0, 1,   2   3  4  5  6  7  8  9  10  11  12 13 14  15 16  17 18, 19
    parents: [3, -1, -1, -1, 3,  4, -1, -1, 5, 5, 12, 10, 3, 3,  15, 13, 9, 8, 17, 16] 
           
    limb_id: [0, 0, 0, 5, 5, 5, 3, 3, 2, 1, 4, 4, 4, 6, 6, 6, 1, 2, 2, 1]
    
    colors:   [[  0.  ,   0.  , 255.  ],
               [  0.  , 127.5 ,   0.  ],
               [  0.  , 191.25, 191.25],
               [191.25,   0.  , 191.25],
               [191.25, 191.25,   0.  ],
               [255.  ,   0.  ,   0.  ],
               [255,     140,         0]]
             
    names: [['HeadF'], #0 
             ['HeadB'], #1
             ['HeadL'], #2
             ['SpineF'], #3
             ['SpineM'], #4
             ['SpineL'], #5 
             ['Offset1'], #6
             ['Offset2'], #7
             ['HipL'], #8
             ['HipR'], #9
             ['ElbowL'], #10
             ['ArmL'], #11
             ['ShoulderL'], #12
             ['ShoulderR'], #13
             ['ElbowR'], # 14
             ['ArmR'], #15
             ['KneeR'], #16
             ['KneeL'], #17
             ['ShinL'], #18
             ['ShinR']] #19