data:
  ndims: 38 # number of 2D/3D points for each time instance. number of joints tracked.
  in_dim: 2 # 2
  out_dim: 3 # 1 or 3.
  dims_to_exclude: [15, 16, 17, 18, 34, 35, 36, 37] #dimensions to not consider during lifting.
  roots: [2] # given targets will be predicted w.r.t roots. therefore len[roots] should be equal to len[targets].
  target_sets: [[0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11]]

vis:
  colors: [
      [186, 30, 49],
      [201, 86, 79],
      [213, 133, 121], 
      [15, 115, 153],
      [26, 141, 175],
      [117, 190, 203], #LF, LM, LH
    ]
  names: ['Nose',  #0 
    'Head', #1
    'Neck',#2
    'RShoulder',#3
    'RHand',#4
    'Shoulder',#5
    'Hand',#6
    'Hip',#7
    'RKnee',#8
    'RFoot',#9
    'Knee',#10
    'Foot',#11
    'Tail']#12
  bones:
    [
      [0, 1], #0 
      [1, 2], #1
      [2, 3], #2
      [3, 4], #3
      [2, 5], #4
      [5, 6], #5
      [2, 7], #6
      [7, 8], #7
      [8, 9], #8
      [7, 10], #9
      [10, 11], #10
      #[7, 12],
    ]
  parents: [1, 2, 7, 7, 5, 7, 5, -1, 8, 7, 7, 10, 7] # for bone_normalization
  limb_id: [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3]
  leaves: [0, 4, 6, 9, 11, 12]
  parents: [1, 2, 7, 2, 3, 2, 5, -1, 7, 8, 7, 10, 7]
