data_dir: '/data/LiftFly3D/DF3D/data_DF3D/'
#data_dir: '/data/LiftFly3D/DF3D/lift_vs_tri'
out_dir: '/data/LiftFly3D/DF3D/cam_angles/cam2'
#out_dir: '/data/LiftFly3D/DF3D/lift_vs_tri/cam5'
#out_dir: '/data/LiftFly3D/DF3D/behaviors/train_MDN'
ndims: 38 #number of dimensions in dataset
in_dim: 2
out_dim: 3
dims_to_exclude: [15,16,17,18,34,35,36,37] #dimensions to not consider
train_subjects: ['all']#[1,2,3,4,5]
test_subjects: ['all']#[6,7]
cam_id: 2
actions: ['all']#['PR', 'MDN_CsCh', 'aDN_CsCh'] #actions to load
interval: []#[200,700]# if only stimulation period
target_sets: [[ 1,  2,  3,  4],  [6,  7,  8,  9], [11, 12, 13, 14]]
roots: [0, 5, 10]
#target_sets: [[16, 17, 18, 19], [21, 22, 23, 24], [26, 27, 28, 29]]
#roots: [15, 20, 25]
