data_dir: '/data/LiftFly3D/DF3D/data_DF3D/'
#data_dir = '/data/LiftFly3D/DF3D/lift_vs_tri/test_dataset/'
out_dir: '/data/LiftFly3D/DF3D/cam_angles/cam5'
#out_dir = '/data/LiftFly3D/DF3D/lift_vs_tri/test_dataset'
#out_dir = '/data/LiftFly3D/DF3D/behaviors/train_PR'
ndims: 38 #number of dimensions in dataset
in_dim: 2
out_dim: 3
dims_to_exclude: [15,16,17,18,34,35,36,37] #dimensions to not consider
train_subjects: [1,2,3,4,5]
test_subjects: [6,7]
cam_id: 5
actions: ['MDN_CsCh', 'MDN_CsCh', 'aDN_CsCh'] #actions to load
interval: [] #[200,700] if only stimulation period
target_sets: [[ 1,  2,  3,  4],  [6,  7,  8,  9], [11, 12, 13, 14],
               [16, 17, 18, 19], [21, 22, 23, 24], [26, 27, 28, 29]]
roots: [0, 5, 10, 15, 20, 25]